name: build and deploy spring app

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: build and deploy spring boot for beginner
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # ou "adopt", "zulu", etc.
          java-version: 17

      - name: unit test
        run: mvn -B test --file pom.xml

      - name: build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build Docker image
        run: |
          docker build -t elmaazouzi.moa.fst@uhp.ac.ma/springcicd:latest .
      - name: push Docker image to Docker Hub
        run: |
          docker push elmaazouzi.moa.fst@uhp.ac.ma/springcicd:latest
